### ISSUE TITLE
Schema validator

### ISSUE THREAD

**Issue by samuelmolinari** [foodoclock/foodoclock.github.io#5]

**Comment by timstott** [comment]
It's not very apparent yet how the schema validator is going to be used. I'm not sure [this interface](https://github.com/foodoclock/recipe-schema/blob/11abb94d0faadc219e4589a15c61217d38962bc1/validator.js#L7) is best. We'll find out soon enough

**Comment by timstott** [comment]
Isn't this issue a duplicate of #11? In which case we can close this.
